Change Functions: rem_winter, RE_format, PS_format
fwitmer/CoastlineExtraction pull request #17
Opened 2024-05-11 15:55 UTC by rawann31

1. Converting date to date object using **datetime.strptime**, can make code so easy, short, and clean to exclude winter images.

2.  I change "**RE_format**", "**PS_format**" to take the id of the image and then return the date of the image as date object.  (I take into consideration that the 2 formats are not the same, "-" is the difference) 

2.1 **time = datetime.strptime(time, "%Y-%m-%dT%H%M%S")** => RE 
2.2 **time = datetime.strptime(time, "%Y%m%dT%H%M%S")** => PS

3. Then I convert the date of the image to the day number in the year such as 2020-02-01 is the second day in the year. By using this: **time.timetuple().tm_yday**

4. Then I check the days of 16 Oct and 15 May and compare if the image date is not between them, then add to clear IDs. 
4. 1 16 Oct is the 290 day of the year.
4.2 15 May is the 136 day of the year

5. I delete the "**list_to_string**" function as It is useless.

Converting date to date time makes the code so easy and short, instead of making many loops and if conditions.

======================================
Future Edits:

BUT:  According to these edits, we should edit the "date_sort" function as It depends on  "RE_format", "PS_format", and "list_to_string".

"date_sort" function also needs many edits also, The new edits will make the code of this function more easy, simpler, and clean

2024-05-21 18:24 UTC, fwitmer requested changes
Please see the comment regarding the if statement on line 379 and let me know what you think.

2024-05-21 18:24 UTC, fwitmer commented on DeeringAutoDownloadCode.py
> +        if not(day_of_year >= 290) and not(day_of_year <= 136):
I think this line would be clearer written without the negatives and with the smaller day first:
`        if day_of_year > 136 and day_of_year < 290:`
Do you agree?

2024-05-28 19:39 UTC, fwitmer commented on DeeringAutoDownloadCode.py
> +        if not(day_of_year >= 290) and not(day_of_year <= 136):
Or, we could use a chained comparison:
`     if 136 < day_of_year < 290:`

2024-05-29 02:44 UTC, rawann31 commented
Yes I totally agree with you in this

2024-05-29 23:05 UTC, fwitmer approved these changes
The revised chained comparison for day_of_year looks good.

2024-05-30 12:32 UTC, closed without merging